import { escapeHtml } from './learning-exports.mjs';
const articles=[['Đọc có chủ đích','Trước khi đọc, hãy viết một câu hỏi bạn muốn trả lời. Sau mỗi phần, ghi lại ý chính bằng lời của mình.\n\nMột bộ sưu tập nhỏ theo chủ đề giúp bạn tìm lại nguồn và nối các ý tưởng. Hãy giữ đường dẫn gốc cùng ghi chú để tiếp tục đọc khi cần.'],['Ôn tập cách quãng','Chia nội dung thành những câu hỏi ngắn. Thử nhớ câu trả lời trước khi mở đáp án.\n\nQuay lại bộ câu hỏi vào các ngày khác nhau và dành thêm thời gian cho những câu bạn chưa nhớ.'],['Ghi chú từ tài liệu','Phân biệt nội dung của nguồn với nhận xét của bạn. Giữ tên tài liệu, đường dẫn và ngày lưu.\n\nTóm lược một đoạn bằng lời của mình rồi ghi lại câu hỏi còn mở để tìm hiểu sau.']];
const layout=(title,body,script='')=>`<!doctype html><html lang="vi"><meta charset="utf-8"><title>${title}</title><style>body{font:19px/1.8 Georgia,serif;max-width:760px;margin:40px auto;padding:20px}article{margin:30px 0}button{font:inherit}a{color:#286775}</style><main>${body}</main>${script?'<script>'+script+'</script>':''}</html>`;
export function demoPdf(){const stream='BT /F1 20 Tf 50 770 Td (Cao Cao - Learning guide) Tj 0 -35 Td /F1 12 Tf (Save sources, write notes, and review with questions.) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let result='%PDF-1.4\n',offsets=[0];objects.forEach((object,index)=>{offsets.push(Buffer.byteLength(result));result+=`${index+1} 0 obj\n${object}\nendobj\n`;});const xref=Buffer.byteLength(result);result+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(offset=>String(offset).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(result);}
export function handleLearningDemo(url,origin){
  const match=url.pathname.match(/^\/demo\/learning\/article\/(\d+)$/);
  if(match){const record=articles[Number(match[1])-1];if(!record)return {status:404,text:'Missing',mime:'text/plain'};return {html:layout(record[0],`<article><h1>${record[0]}</h1><p>${record[1].split('\n\n').join('</p><p>')}</p><p><a href="${origin}/demo/learning/guide.pdf">Tài liệu PDF minh họa</a></p></article>`)};}
  if(url.pathname==='/demo/learning/articles')return {html:layout('Tủ sách học tập',`<h1>Tủ sách học tập</h1>`+articles.map((item,index)=>`<article><h2><a href="/demo/learning/article/${index+1}">${item[0]}</a></h2><p>${item[1].slice(0,140)}</p></article>`).join(''))};
  if(url.pathname==='/demo/learning/guide.pdf')return {buffer:demoPdf(),mime:'application/pdf'};
  const questions=articles.flatMap((item,index)=>[{id:index*2+1,question:`Ý chính của bài “${item[0]}” là gì?`,options:[item[1].split('.')[0], 'Chỉ lưu tên bài, không cần nội dung'],answer:item[1].split('.')[0]},{id:index*2+2,question:`Bạn sẽ áp dụng bài “${item[0]}” như thế nào?`,options:[],answer:''}]);
  if(url.pathname==='/demo/learning/questions-api'){const page=Number(url.searchParams.get('page')||1);return {json:{items:questions.slice((page-1)*3,page*3),hasMore:page*3<questions.length,total:questions.length}};}
  if(url.pathname==='/demo/learning/questions')return {html:layout('Bộ câu hỏi học tập','<h1>Bộ câu hỏi học tập</h1><section id="questions"></section><button id="next">Trang tiếp theo</button>',`let page=1;async function load(){const data=await(await fetch('/demo/learning/questions-api?page='+page)).json();document.getElementById('questions').replaceChildren(...data.items.map(item=>{const article=document.createElement('article'),h=document.createElement('h2'),p=document.createElement('p');h.textContent=item.question;p.textContent=item.options.join(' / ');article.append(h,p);return article;}));document.getElementById('next').disabled=!data.hasMore;}document.getElementById('next').onclick=()=>{page++;load();};load();`)};
  return null;
}
